name: "netboot.xyz PXE Server"
version: "1.0.4"
slug: "netboot"
description: "netboot.xyz als PXE/TFTP/HTTP Server fuer externe DHCP-Umgebungen."
url: "https://github.com/BitcircuitEU/ha-addons/tree/main/netboot"
startup: services
boot: auto
init: false
arch:
  - amd64
  - aarch64
host_network: true
webui: "http://[HOST]:[PORT:3000]"
ingress: true
ingress_port: 8099
panel_icon: mdi:lan
panel_title: netboot.xyz
options:
  menu_version: ""
  web_app_port: 3000
  nginx_port: 80
  tftpd_opts: ""
schema:
  menu_version: str
  web_app_port: int
  nginx_port: int
  tftpd_opts: str
